import { Discount } from '@descuentos-santiago/domain'

export const seedDiscounts = [
  Discount.create({
    id: 'disc-001',
    title: 'Cafe de barrio 2x1',
    description: 'Activa un bloque de cafe y desayuno con prioridad alta para Providencia.',
    businessName: 'Cafe Lastarria Norte',
    comuna: 'Providencia',
    category: 'Comida',
    percentageOff: 40,
    sourceUrl: 'https://example.com/cafe-lastarria-norte',
    tags: ['2x1', 'manana', 'cafe'],
    priority: 'high',
    featured: true,
    status: 'published',
    startsAt: new Date('2026-06-05T08:00:00.000Z'),
    expiresAt: new Date('2026-06-06T01:00:00.000Z'),
  }),
  Discount.create({
    id: 'disc-002',
    title: 'Dermocosmetica de fin de semana',
    description: 'Campana con enfoque de conversion para farmacia premium.',
    businessName: 'Cruz Verde Apoquindo',
    comuna: 'Las Condes',
    category: 'Farmacia',
    percentageOff: 30,
    sourceUrl: 'https://example.com/cruz-verde-apoquindo',
    tags: ['flash', 'skin-care'],
    priority: 'medium',
    featured: true,
    status: 'published',
    startsAt: new Date('2026-06-05T12:00:00.000Z'),
    expiresAt: new Date('2026-06-07T03:00:00.000Z'),
  }),
  Discount.create({
    id: 'disc-003',
    title: 'Outlet invierno en mall',
    description: 'Oferta de retail para empujar trafico de temporada.',
    businessName: 'Mall Plaza Egaña',
    comuna: 'Nunoa',
    category: 'Retail',
    percentageOff: 55,
    sourceUrl: 'https://example.com/mall-plaza-egana',
    tags: ['temporada', 'stock'],
    priority: 'high',
    featured: false,
    status: 'published',
    startsAt: new Date('2026-06-05T14:00:00.000Z'),
    expiresAt: new Date('2026-06-08T00:00:00.000Z'),
  }),
  Discount.create({
    id: 'disc-004',
    title: 'Pack manicure + corte',
    description: 'Promocion de belleza orientada a horarios valle.',
    businessName: 'Studio Alameda',
    comuna: 'Santiago Centro',
    category: 'Belleza',
    percentageOff: 25,
    sourceUrl: 'https://example.com/studio-alameda',
    tags: ['bundle', 'after-office'],
    priority: 'low',
    featured: false,
    status: 'draft',
    startsAt: new Date('2026-06-06T15:00:00.000Z'),
    expiresAt: new Date('2026-06-09T00:00:00.000Z'),
  }),
  Discount.create({
    id: 'disc-005',
    title: 'Entradas cine familiar',
    description: 'Bloque editorial para fin de semana y panoramas.',
    businessName: 'Cine Arte Plaza',
    comuna: 'La Florida',
    category: 'Panorama',
    percentageOff: 20,
    sourceUrl: 'https://example.com/cine-arte-plaza',
    tags: ['familia', 'fin-de-semana'],
    priority: 'medium',
    featured: true,
    status: 'published',
    startsAt: new Date('2026-06-05T16:00:00.000Z'),
    expiresAt: new Date('2026-06-07T22:00:00.000Z'),
  }),
]
